name: Parse swagger on push
on:
  push:
    branches:
      - main
jobs:
  parse-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install
        run: |
          npm install
          npm install -g redoc-cli
      - name: build-html
        run: |
          npm run build
          redoc-cli bundle -o index.html dist.yaml
      - name: git actions
        run: |
          git config user.email "cottynmaurits@gmail.com"
          git config user.name "mauritscottyn"
          git add .
          git commit -m "adding html"
          git push
